const PendenciasTypes = {
    ADD_NEW_PENDENCIA : 'ADD_NEW_PENDENCIA',
    DELETE_NEW_PENDENCIA : 'DELETE_NEW_PENDENCIA',
    DELETE_ALL_NEW_PENDENCIAS: 'DELETE_ALL_NEW_PENDENCIAS',
    LOAD_OLD_PENDENCIAS: 'LOAD_OLD_PENDENCIAS',
    DELETE_ALL_OLD_PENDENCIAS: 'DELETE_ALL_OLD_PENDENCIAS',
    SET_NEW_PENDENCIAS : 'SET_NEW_PENDENCIAS',
    SAVE_NEW_PENDENCIAS : 'SAVE_NEW_PENDENCIAS'
}

export default PendenciasTypes;